version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_app_leadlly
    container_name: backend_leadlly
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGODB_URI=mongodb://${DB_ADMIN}:${DB_PASSWORD}@mongo:27017/${DB_NAME}?authSource=admin
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    image: mongo
    container_name: mongo_leadlly
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - my-network

volumes:
  mongodb-data:

networks:
  my-network:
    name: my-network
