version: '3.9'

services:
 mongo:
    image: mongo
    container_name: mongo_leadlly
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

 app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_app_leadlly
    container_name: backend_leadlly
    restart: unless-stopped
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://admin:password@mongo:27017/leadlly
    ports:
      - 8080:8080
    depends_on:
      - mongo

volumes:
 dbdata:
