name: CI on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Generate Mongoose Models
      run: npm run build
    
    - name: Run Build
      run: npm run build 
